name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones disabled for better relevancy
      - name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.jdbc.url=${{ secrets.DATABASE_URL }}

  vercel:
    name: Deploy production to Vercel
    needs: sonarqube
    runs-on: ubuntu-latest
    # Only deploy on push to main, not on pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Prepare repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones disabled for better relevancy
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Install Vercel CLI
        run: pnpm install -g vercel
      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build project artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy project artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}